# Generated by Django 4.0.4 on 2022-08-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitinstance',
            name='branch',
            field=models.CharField(default='main', help_text='Enter the branch name or commit ID.', max_length=255, verbose_name='Commit Or Branch'),
        ),
    ]
