# Generated by Django 4.0.4 on 2022-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminview', '0003_create_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitinstance',
            name='name',
            field=models.CharField(help_text='Unique name of the git repo.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gitinstance',
            name='url',
            field=models.CharField(help_text='URL to the git repo.', max_length=255),
        ),
    ]
