# Generated by Django 4.0.4 on 2022-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminview', '0004_alter_gitinstance_name_alter_gitinstance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitinstance',
            name='last_build',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitinstance',
            name='last_reload',
            field=models.DateField(blank=True, null=True),
        ),
    ]
