# Generated by Django 4.0.4 on 2022-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminview', '0005_gitinstance_last_build_gitinstance_last_reload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitinstance',
            name='last_build',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitinstance',
            name='last_reload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
