# Generated by Django 4.0.4 on 2022-08-24 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('appr', models.CharField(max_length=4, verbose_name='Abbreviation')),
                ('includes', models.ManyToManyField(to='Dashboard.qualification')),
                ('user', models.ManyToManyField(related_name='qualification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
