# Generated by Django 4.0.4 on 2022-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(help_text='WebDAV Password', max_length=100)),
                ('src', models.CharField(help_text='Source directory to be watched.', max_length=255)),
                ('dst', models.CharField(help_text='WebDAV destination URL. If the destination is on the lsdf, the URL should be as follows:\n        https://os-webdav.lsdf.kit.edu/<OE>/<inst>/projects/<PROJECTNAME>/\n                    <OE>-Organisationseinheit, z.B. kit.\n                    <inst>-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.\n                    <USERNAME>-User-Name z.B. xy1234, bs_abcd etc.\n                    <PROJRCTNAME>-Projekt-Name', max_length=255)),
                ('type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder'), ('folder', 'ZIP')], help_text="Type must be 'file', 'folder' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The option 'zip' sends a folder zipped, only when all files in a folder are ready.", max_length=255)),
                ('duration', models.IntegerField(default=300, help_text='Duration in seconds, i.e., how long a file must not be changed before sent. (default 300 sec.)')),
                ('cert', models.CharField(help_text='Path to server TLS certificate. Only needed if the server has a self signed certificate.', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
