# Generated by Django 4.0.4 on 2022-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_instance_remove_qualification_includes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='cert',
            field=models.CharField(blank=True, help_text='Path to server TLS certificate. Only needed if the server has a self signed certificate.', max_length=255, null=True),
        ),
    ]
