# Generated by Django 4.0.4 on 2022-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_instance_cert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='type',
        ),
        migrations.AddField(
            model_name='instance',
            name='efw_type',
            field=models.CharField(choices=[('file', 'File'), ('folder', 'Folder'), ('zip', 'ZIP')], default='file', help_text="Type must be 'file', 'folder' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The option 'zip' sends a folder zipped, only when all files in a folder are ready.", max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='dst',
            field=models.CharField(help_text='WebDAV destination URL. If the destination is on the lsdf, the URL should be as follows:\n        https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECTNAME]/<br>\n                    [OE]-Organisationseinheit, z.B. kit.<br>\n                    [inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.<br>\n                    [USERNAME]-User-Name z.B. xy1234, bs_abcd etc.<br>\n                    [PROJRCTNAME]-Projekt-Name', max_length=255),
        ),
    ]
