# Generated by Django 4.0.4 on 2022-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_instance_efw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='architecture',
            field=models.CharField(choices=[('win_i386', 'Windows i386'), ('win_64', 'Windows 64 Bit')], default='win_i386', help_text='Your computer architecture : either 64 bit or 32 bit (i386) ', max_length=255, verbose_name='System architecture'),
        ),
    ]
