# Generated by Django 4.0.4 on 2022-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_instance_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.CharField(default='', help_text='WebDAV User', max_length=50),
        ),
    ]
