# Generated by Django 4.0.4 on 2022-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_instance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
