# Generated by Django 4.0.4 on 2022-08-31 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_instance_last_build_alter_instance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
