# Generated by Django 4.0.4 on 2022-08-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_instance_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='cert',
        ),
    ]
