# Generated by Django 4.0.4 on 2022-09-05 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_remove_instance_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
