# Generated by Django 4.0.4 on 2022-09-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_instance_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmlDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UmlElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='Dashboard.umldiagram')),
            ],
        ),
        migrations.CreateModel(
            name='UmlSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.umlelement')),
            ],
        ),
        migrations.CreateModel(
            name='UmlLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.umlsegment')),
            ],
        ),
        migrations.CreateModel(
            name='UmlField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_table_field', models.BooleanField()),
                ('field', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.umlsegment')),
                ('sub_field', models.ManyToManyField(blank=True, related_name='included_by', to='Dashboard.umlfield')),
            ],
        ),
    ]
