# Generated by Django 4.0.4 on 2022-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_umldiagram_umlelement_umlsegment_umllayer_umlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='umlelement',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='umlelement',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
