# Generated by Django 4.0.4 on 2022-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_rename_segment_umlfield_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='umlfield',
            name='type',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
