# Generated by Django 4.0.4 on 2022-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_umlfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umlfield',
            name='sub_field',
        ),
        migrations.AddField(
            model_name='umlfield',
            name='sub_field_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_field', to='Dashboard.umlfield'),
        ),
    ]
