# Generated by Django 4.0.4 on 2022-09-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_umlfield_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umlfield',
            name='sub_field_from',
        ),
        migrations.AddField(
            model_name='umlfield',
            name='sub_field_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_field', to='Dashboard.umlfield'),
        ),
    ]
