# Generated by Django 4.0.4 on 2022-09-12 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_remove_umlfield_sub_field_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umlelement',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='umlfield',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Dashboard.umllayer'),
        ),
        migrations.AlterField(
            model_name='umlfield',
            name='sub_field_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields', to='Dashboard.umlfield'),
        ),
        migrations.AlterField(
            model_name='umllayer',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='Dashboard.umlsegment'),
        ),
        migrations.AlterField(
            model_name='umlsegment',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='Dashboard.umlelement'),
        ),
    ]
