# Generated by Django 4.0.4 on 2022-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_umlelement_extends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(help_text='Unique name of the EFW instance. This name cannot be changed!', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='src',
            field=models.CharField(help_text='Source directory to monitor. Note: If you use only single \\ in the path, the build will fail. Therefore, make sure that you always use \\\\.', max_length=255),
        ),
    ]
