# Generated by Django 4.0.4 on 2022-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_alter_instance_name_alter_instance_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='transfer',
            field=models.CharField(choices=[('webdav', 'WebDAV'), ('sftp', 'SFTP')], default='webdav', help_text='You can either use the WebDAV protocol or the SFTP protocol', max_length=255, verbose_name='Transfer protocol'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='architecture',
            field=models.CharField(choices=[('win_i386', 'Windows i386'), ('win_64', 'Windows 64 Bit'), ('ubuntu_64', 'Ubuntu 64 Bit')], default='win_i386', help_text='Your computer architecture : either 64 bit or 32 bit (i386) ', max_length=255, verbose_name='System architecture'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='password',
            field=models.CharField(help_text='WebDAV or STFP Password', max_length=100),
        ),
        migrations.AlterField(
            model_name='instance',
            name='user',
            field=models.CharField(default='', help_text='WebDAV or STFP User', max_length=50),
        ),
    ]
