# Generated by Django 4.0.4 on 2022-11-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_instance_transfer_alter_instance_architecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umlelement',
            name='diagram',
        ),
        migrations.RemoveField(
            model_name='umlelement',
            name='extends',
        ),
        migrations.RemoveField(
            model_name='umlfield',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='umlfield',
            name='sub_field_from',
        ),
        migrations.RemoveField(
            model_name='umllayer',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='umlsegment',
            name='element',
        ),
        migrations.AlterField(
            model_name='instance',
            name='dst',
            field=models.CharField(help_text='WebDAV or SFTP destination URL. If the destination is on the lsdf, the URL should be as follows:<br>ss\n        SFTP: os-login.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECTNAME]/<br>\n        WebDAV: https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECTNAME]/<br>\n                    [OE]-Organisationseinheit, z.B. kit.<br>\n                    [inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.<br>\n                    [USERNAME]-User-Name z.B. xy1234, bs_abcd etc.<br>\n                    [PROJRCTNAME]-Projekt-Name', max_length=255),
        ),
        migrations.DeleteModel(
            name='UmlDiagram',
        ),
        migrations.DeleteModel(
            name='UmlElement',
        ),
        migrations.DeleteModel(
            name='UmlField',
        ),
        migrations.DeleteModel(
            name='UmlLayer',
        ),
        migrations.DeleteModel(
            name='UmlSegment',
        ),
    ]
