# Generated by Django 4.1.4 on 2023-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashboard",
            "0024_remove_umlelement_diagram_remove_umlelement_extends_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="dst",
            field=models.CharField(
                help_text='WebDAV or SFTP destination URL. If the destination is on the lsdf, the URL should be as follows:<br>\n        <span style="margin-left: 20px; font-weight: 800;">SFTP</span>: os-login.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n        <span style="margin-left: 20px; font-weight: 800;">WebDAV</span>: https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n\n                    <span style="margin-left: 30px;">[OE]-Organisationseinheit, z.B. kit.</span><br>\n                    <span style="margin-left: 30px;">[inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.</span><br>\n                    <span style="margin-left: 30px;">[USERNAME]-User-Name z.B. xy1234, bs_abcd etc.</span><br>\n                    <span style="margin-left: 30px;">[PROJECT_PATH]-Path (directory) within the LSDF</span>',
                max_length=255,
            ),
        ),
    ]
