# Generated by Django 4.1.4 on 2023-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0025_alter_instance_dst"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="backup",
            field=models.CharField(
                choices=[
                    ("user_backup", "(A) only if it can be assigned to an ELN user,"),
                    ("all_backup", "(B) in any case"),
                    ("no_backup", "(C) no backup"),
                ],
                default="user_backup",
                help_text="There are three different backup settings. Either, (A) a backup of the data is created only if it can be assigned to an ELN user, (B) a backup of the data is created in any case or (C) a backup is not created in any case.",
                max_length=255,
                verbose_name="Backup type",
            ),
        ),
    ]
