# Generated by Django 4.1.4 on 2023-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_email_confirmed",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="EmailLink",
        ),
    ]
